### ISSUE TITLE
Camelize `json` returns `Json`

### ISSUE THREAD

**Issue by GustavoCaso** [dry-rb/dry-inflector#16]
We should provide a way for making these **abbreviations** or **acronym** to return the correct word.

In this case `JSON`

**Comment by Ptico** [comment]
I'm planning to implement acronyms support as soon as we will agree on https://discourse.dry-rb.org/t/dry-inflector-future-api/398

**Comment by Ptico** [comment]
@GustavoCaso From the other side, nothing blocks me to do this right now. Will PR it soon

**Comment by GustavoCaso** [comment]
We can close these issue it was addressed with #22
