### ISSUE TITLE
[flexus port] Address singularization

### ISSUE THREAD

**Issue by abinoam** [dry-rb/dry-inflector#3]
This definitely should be ported. Everybody agree?

See mbj/inflecto#16 Ptico/flexus#2

**Comment by jodosha** [comment]
@abinoam yup, please port it as well. 👍

**Comment by solnic** [comment]
Fun fact: I had to use ActiveSupport::Inflector a couple times just because of address singularization issue 😆

**Comment by abinoam** [comment]
The current api doesn't have a way to fire up a blank instance of Dry::Inflector (without any rules loaded). So, if we don't update the defaults, anybody can begin with a blank state and add their own rules.
(I was already thinking about this at flexus. And let the "loading defaults" step optional on the last commits we did there).
This can be useful for internationalization.
Although the main use is english, perhaps we should provide room for internationalization.

**Comment by jodosha** [comment]
@abinoam Loading w/o defaults can be an enhancement.

But how the current design prevents to fix that pluralizations?

**Comment by abinoam** [comment]
@jodosha, If I try to provide portuguese pluralization and I miss a special case, inflector will fallback to the inner default english rules. I think the appropriate behaviour would be just return the given string when no portuguese rules apply. But, this will not happen. It will keep trying the rules that were loaded at initialization. Perhaps I'm missing something. But I can try to craft an example.

**Comment by jodosha** [comment]
@abinoam Thanks for the explanation.

What if we just port that fixes from https://github.com/Ptico/flexus/pull/2, ship the `v0.1.0`, and then we consider multilingual support? If this new feature will require a change in the way defaults are loaded, well we will modify it. WDYT? 😉

**Comment by Ptico** [comment]
Hi, sorry, I'm a little bit busy today, what if I will make a diff and port all improvements to the current codebase? And then we can release 0.1.0.

And then, I'll finish a big text with my thoughts and suggestions on the future improvements and will open the issue with it.

**Comment by abinoam** [comment]
@jodosha, I agree. For first release only the things that were already
running.
I was just comenting but was not my intention to make this a kind of
priority or so.

**Comment by jodosha** [comment]
Hi all,
As clarification, is anyone working on this? If not, I'll be able to do it in Monday.

Please let me know, if you already started.

Cheers.

http://lucaguidi.com

**Comment by abinoam** [comment]
See #4.
