### ISSUE TITLE
singularize method return 'bonuses' as 'bonuse'

### ISSUE THREAD

**Issue by D5ky** [dry-rb/dry-inflector#33]
**Describe the bug**
`Dry::Inflector.new.singularize('bonuses') => "bonuse"`

**To Reproduce**

Call `Dry::Inflector.new.singularize('bonuses')`

**Expected behavior**

`Dry::Inflector.new.singularize('bonuses') => 'bonus'`

**Your environment**

- Affects my production application: **NO**
- Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
- OS: macOS Catalina 10.15.7

**Comment by cllns** [comment]
:+1: Similar words which also fail this way: 
- `Dry::Inflector.new.singularize('geniuses') # => 'geniuse'`
- `Dry::Inflector.new.singularize('walruses') # => 'walruses'`
