### ISSUE TITLE
cache results

### ISSUE THREAD

**Issue by dsisnero** [dry-rb/dry-inflector#34]
## Describe the bug
When tracing path through dry-system, the path kept on going through dry-inflector for looking up keys.  Would it be possible to cache the result of first lookup so that this is fast?

## To Reproduce

Provide detailed steps to reproduce, **an executable script would be best**.

## My environment

- Affects my production application: **YES/NO**
- Ruby version: ...
- OS: ...

**Comment by solnic** [comment]
We'll add optional caching eventually.

ps. in the future, please don't use issue trackers to ask questions - we have discourse.dry-rb.org for this type of communication
