### ISSUE TITLE
Release of 0.1.0

### ISSUE THREAD

**Issue by abinoam** [dry-rb/dry-inflector#5]
Updated 2017-11-16

- [x] Merge #4 (address singularization)?
- [x] Will we have a #constantize method?
- [x] Will we have a #foreign_key method?
- [x] #6 - Symbol input
- [x] #7 - "people" pluralization

See comment https://github.com/dry-rb/dry-inflector/issues/1#issuecomment-343634079 and on.

Then @jodosha can fire a release tomorrow.

**Comment by solnic** [comment]
Unfortunately #6 and #7 are blockers right now :/

**Comment by jodosha** [comment]
I've worked on fixes for #6 and #7, which are #10 and #11 respectively. I need your review folks.

@abinoam Would you work on `#constantize` and `#foreign_key`?

**Comment by abinoam** [comment]
I'll have some time this afternoon. I will review PRs and add #constantize and #foreign_key. 👍

**Comment by abinoam** [comment]
After merging #13 the only blocker for the release will be #7.

@solnic is the current api enough for rom-rb compatibility?

I mean, if you just override "people" pluralization with a block at initialization of the inflector would solve for you?

If so, we could release, and then keep going on the discussion of the more complex api with different set of inflections rules.

**Comment by solnic** [comment]
> I mean, if you just override "people" pluralization with a block at initialization of the inflector would solve for you?

yes it would, I'll verify if specs are passing against dry-inflector master

**Comment by solnic** [comment]
Looks like we're done. rom-rb specs are green in both main suite and rom-sql.
