### ISSUE TITLE
Symbols no longer supported

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-inflector#6]
Looks like some methods no longer work with symbols, ie `camelize(:users)` used to work in inflecto (FWIW it also works in ActiveSupport::Inflector)

**Comment by abinoam** [comment]
I'll have a look.

**Comment by abinoam** [comment]
Oops... I see you have worked this out at your backward-compat branch.

**Comment by jodosha** [comment]
In my initial implementation, I assumed `String` as the input type for all the methods (except for `#ordinalize`).

Do you think should be added?

**Comment by solnic** [comment]
yeah I think we should be doing `to_s` (or `String(input)`) everywhere, it would make using this lib much nicer
